### ISSUE TITLE
ES changed repos.... again

### ISSUE THREAD

**Issue by vacri** [bakhti/ansible-elk#15]
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html

Now it's `packages.elastic.co` instead of `packages.elasticsearch.com`, which 404s. Everything else appears to be the same.

Also, using the playbook with debian/openJDK, it breaks at the 'accept oracle license' step - need to change 

``` yaml
 when: webupd8team.stdout != 'true'
```

to

``` yaml
"when: elk_java.flavor == 'oracle' and webupd8team.stdout != 'true' and ansible_distribution == 'Ubuntu'"
```

(better matches the previous steps)

Thanks for the playbook, by the way.

**Comment by bakhti** [comment]
Thank you for reporting this!
