### ISSUE TITLE
Logstash embedded Elasticsearch version

### ISSUE THREAD

**Issue by martingalloar** [bakhti/ansible-elk#9]
The version of Elasticsearch which is embedded in logstash (currently 1.1.1) doesn't match with the one expected by Kibana (>1.4), making the latter fail. I workaround this by manually doing `cp -R /usr/share/elasticsearch/ /opt/logstash/vendor/jar/elasticsearch-1.4.4` and then removing the old ES version in `/opt/logstash/vendor/jar`.
Maybe it's possible to add this task to the role so it keeps everything working? Do you think of a better approach for solving this? Let me know and I can work on a PR.

**Comment by bakhti** [comment]
Interesting solution, maybe I'll try it. For now I've been using "protocol => http" to avoid embedded Elasticsearch. I was also planning to check Logstash 1.5.0 (https://www.elastic.co/downloads/logstash).

**Comment by martingalloar** [comment]
That's an easier way of dealing with the issue, thanks !
